### ISSUE TITLE
Audit all laser barriers to ensure they fully block the path

### ISSUE THREAD

**Issue by rmkubik** [TwilioQuest/twilioquest-open-source#13]
The laser barriers in the map forest1 do not fully block the paths they're positioned on in the mission. We should ensure the rest of the laser barriers in this mission work as well with this issue.

Using the blocker object from the Pythonic Temple should help resolve this issue.

**Comment by git-pixel22** [comment]
Hey! I posted about the same issue on Twitter just a while back, what a coincidence!

**Comment by MarvelProgramming** [comment]
Resolved by #31
