### ISSUE TITLE
Replace command-exists with a more robust solution 

### ISSUE THREAD

**Issue by rmkubik** [TwilioQuest/twilioquest-open-source#14]
`command-exists` frequently gives players troubles that are hard for us to diagnose. Especially on windows. We should change open source missions to use something more robust. We do not get the same complaints for JavaScript and Python when we ask explicitly for the executable path. This is a probably the bare minimum change to make, unless some other method is found when implementing this ticket.

**Comment by MarvelProgramming** [comment]
So would we essentially be mirroring what's being done for node and python env setup? That is, we ask that the player provide the path to their git executable as part of the objective, and the validator will use the `isExecutableValid` helper method?

**Comment by rmkubik** [comment]
Yes, I think we should switch to this strategy!

We'll need to update the objective's description/walkthrough to ask players for their `git` executable path and such too.
