### ISSUE TITLE
Add Daizen's NPC

### ISSUE THREAD

**Issue by kerrielake** [TwilioQuest/twilioquest-open-source#18]
Daizen will be added near the entrance of the Fog Owl and have a bit of dialogue that needs to be implemented.

**Comment by MarvelProgramming** [comment]
For Daizen's character name, I noticed that it says "Daizen Ikehara, **Translations Expert**". Should I put the full name, or just "Daizen" (it's currently set to just "Daizen")

<img width="722" alt="daizen-npc-character-name" src="https://user-images.githubusercontent.com/51891409/196786097-c535b0f0-fd9d-4863-8006-70719a5b5e5b.png">

<img width="226" alt="daizen-npc-name" src="https://user-images.githubusercontent.com/51891409/196786125-dfd07d0d-b0de-41bd-9245-9f93c637ddbc.png">

**Comment by kerrielake** [comment]
I think keeping it just Daizen should be fine
