### ISSUE TITLE
Possible incorrect tile on initial map file

### ISSUE THREAD

**Issue by ShelbyZ** [TwilioQuest/twilioquest-open-source#2]
I am not sure how to get the X/Y coordinates as the `Toggle Developer Tools` console only stay open briefly before going dark, but the screenshot below shows the tile. If there is a way to get on screen X/Y coordinates it may be possible to figure out which tile should be corrected.

![wrong tile](https://user-images.githubusercontent.com/1033099/148012229-eb50a9a0-1853-47f5-9ebf-1c5fd41cf6d4.png)

**Comment by MarvelProgramming** [comment]
Fixed in #6
