### ISSUE TITLE
Stone near Fog Owl is missing collision

### ISSUE THREAD

**Issue by kerrielake** [TwilioQuest/twilioquest-open-source#20]

**Comment by kerrielake** [comment]
Also fix any other missing collisions that may be there

**Comment by MarvelProgramming** [comment]
Is this the rock that's missing a collider? Checked a few of the other maps and they didn't have colliders for them either, so I wanted to check before making any changes

<img width="696" alt="missing-rock-collider" src="https://user-images.githubusercontent.com/51891409/196237302-8f3fc0d8-2af3-4773-9b36-927cdd94cd4f.png">

**Comment by kerrielake** [comment]
@MarvJohnson It is! I was planning to fix this too but didn't have a chance to check the collision on the other maps yet. If you want to tackle this one let me know and I'll leave it out of the updates I'm planning!

**Comment by MarvelProgramming** [comment]
I can knock this out pretty quickly! There are a few things I'm working on right now that require a lot of scouring maps anyhow

**Comment by kerrielake** [comment]
Sounds good! Thanks Marvel :)
