### ISSUE TITLE
Update Shopkeeper npc

### ISSUE THREAD

**Issue by kerrielake** [TwilioQuest/twilioquest-open-source#22]
One of the npcs behind the stall in the marketplace in in their underwear and has no antlers!

**Comment by MarvelProgramming** [comment]
Should we replace the sprite for the npc with another that has these things set up, or was there another approach you were thinking of? Let me know and I'll hop on in and make the changes  🙌

**Comment by kerrielake** [comment]
I'd say switch it to one of the druids we have for now! I'd like to
eventually add more but don't think I'll have time to make a completely new
one this week.
