### ISSUE TITLE
Inconsistencies When Verifying User Name

### ISSUE THREAD

**Issue by Cynthia7979** [TwilioQuest/twilioquest-open-source#5]
The rules for verifying whether: 1. a user exists, and 2. the user created a specific pull request, are different.

**How to Reproduce**
1. Have a username that contains both uppercase and lowercase letters
2. When the game asks for your GitHub username, type it in *all lowercase* letters
3. Later, when the game asks for the PR you created at [twilio-labs/open-pixel-art](https://github.com/twilio-labs/open-pixel-art), type your PR number in
4. The game notifies you that you're not the person who created that PR. This is because it verifies PR author in a case-sensitive way, whereas verifying if a user exists is case-insensitive (e.g., both https://github.com/cynthia7979 and https://github.com/Cynthia7979 would lead to my profile)

**How I Fixed It (In Game)**

I went back to the username task and typed in my username with letters correctly capitalized.

--------

I'd be glad to submit a PR if any help is needed. Thank you for developing TwilioQuest!

**Comment by MarvelProgramming** [comment]
I can't seem to reproduce this when following the steps provided. I took a look at the validator for this objective and the condition that checks for equality between the owner of the PR and the TwilioQuest player lowercases both values, so I don't think this is the issue

**Comment by rmkubik** [comment]
I went ahead and closed this because we couldn't reproduce the issue. We've made a change semi-recently to resolve comparisons of GitHub usernames, so this might've fixed the case reported here. If this is wrong, we can re-open the issue!
